### ISSUE TITLE
[User-Story] - DSL for Load Mapping

### ISSUE THREAD

**Issue by franksn90** [dqualizer/dqlang#2]
## Story

As a USER who PRECONDITIONS, I want to DO_THING so I can ACCOMPLISH_GOAL.

## Acceptance Criteria

- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3

## Dependencies

- [ ] Blocked by issue one
- [ ] Blocked by issue two
- [ ] Blocked by issue three

## Additional context

Add any other context or screenshots about the research request here.

**Comment by EddeCCC** [comment]
https://github.com/dqualizer/dqlang/tree/main/schemas/domain-architecture-mapping
