### ISSUE TITLE
RQA Config (Loadtests) v2

### ISSUE THREAD

**Issue by EddeCCC** [dqualizer/dqlang#24]
Loadtest-Configuration nach Erkenntnissen im Gatling-Adapter überarbeiten

**Comment by GeorgiaKoenig** [comment]
Sztatus-Update: RQA's sind angepasst, aber noch nicht eingechecked, Review erwünscht für meine Arbeit hier,

**Comment by EddeCCC** [comment]
In dqlang wurde ein Branch `update_loadtest` mit den Änderungen erstellt.
